spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://database-1.c6qikducylfb.ap-south-1.rds.amazonaws.com:1433;dataBase=practisejpa;userName=admin;password=87654321;trustServerCertificate=true
    continue-on-error: true
    hikari:
      initialization-fail-timeout: -1
      minimum-idle: 0
      connection-timeout: 3000
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

server:
  port: 9090
